import Head from 'next/head'
import About from '../../components/About'
import ContactUs from '../../components/ContactUs'
import Galery from '../../components/Galery'
import Header from '../../components/Header'
import Testimonials from '../../components/Testimonials'
import Ubication from '../../components/Ubication'
import Fotter from '../../components/Fotter'

export default function Home() {
  return (
    <>
      <Head>
        <title>Tu Sitio Web  </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/circles.svg" />
      </Head>
      <Header />
      <main>
        {<About />}
        {<Galery />}
        {<Testimonials />}
        <Ubication />
        <ContactUs />
        <Fotter />
      </main>
    </>
  )
}
